language: cpp

compiler:
  - clang

env:
  - BUILD_TYPE=RelWithDebInfo
  - BUILD_TYPE=Release

before_install:
  - xcode-select --install
  - brew update
  - brew install cmake

install:
  - cd projects
  - cmake -GUnix\ Makefiles -HCMake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make -j4
  - cd ../..

script:
  - cd Build
  - ctest -V
  - cd ..

branches:
  only:
    - master
notifications:
  recipients:
    - kirk.shoop@microsoft.com
  email:
    on_success: change
    on_failure: always

os:
  - osx
