
language: cpp

os:
  - linux
  - osx

compiler:
  - clang

env:
  - BUILD_TYPE=Release

before_install:
  - sh projects/scripts/travis-install.sh

install:
  - cd projects
  - cmake -GUnix\ Makefiles -HCMake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make -j4
  - cd ../..

script:
  - cd projects/build
  - ctest -V
  - cd ../..

branches:
  only:
    - master

notifications:
  recipients:
    - kirk.shoop@microsoft.com
  email:
    on_success: always
    on_failure: always
