language: cpp

compiler:
  - clang

env:
  - BUILD_TYPE=RelWithDebInfo
  - BUILD_TYPE=Release

install:
  - cmake -Hprojects/CMake -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd Build
  - make
  - cd ..

script:
  - cd Build
  - ctest -V

branches:
  only:
    - master
notifications:
  recipients:
    - kirk.shoop@microsoft.com
  email:
    on_success: change
    on_failure: always

os:
  - osx
